### ISSUE TITLE
No code generated

### ISSUE THREAD

**Issue by rgsoft** [thiagoloureiro/Dapper.Crud.Extension#1]
I have isntalled this extension dialog pops up ok, select Models etc and click Generate.  However nothing happens - no code (or errors) is displayed in the code window - can you please advise - thanks

**Comment by thiagoloureiro** [comment]
hello @rgsoft , don't know why VisualStudio it's not showing in the Output the error message, I have included in the new version (2.0) the errorLog text, than it's easier to identify the source, and please put the output here then I can help you!

**Comment by thiagoloureiro** [comment]
@rgsoft I have updated the extension, please check if now it works for you.
