### ISSUE TITLE
Erro ao gerar Código

### ISSUE THREAD

**Issue by paulocarinhena** [thiagoloureiro/Dapper.Crud.Extension#18]
Thiago tudo bem?

Eu tenho a seguinte classe:

```
namespace WCore.Model
{
    public class Cargos
    {
        public int idCargo { get; set; }
        public string codCargo { get; set; }
        public string cargo { get; set; }
        public decimal? valor { get; set; }
        public string codUni { get; set; }
        public int? recursot { get; set; }
    }
}
```

Quando eu tento gerar ele da o seguinte erro:

"
Error during the operation: Compiler Errors :
Line 24,23	: Identifier expected
Line 24,23	: ; expected
Line 24,49	: ) expected
Line 24,49	: Type or namespace definition, or end-of-file expected
Line 24,82	: Identifier expected
Line 24,82	: Syntax error, ',' expected
Line 24,83	: Tuple must contain at least two elements.
Line 24,84	: Identifier expected
Line 24,85	: ; expected
Line 25,23	: ; expected
Line 24,85	: Type or namespace definition, or end-of-file expected
Line 25,41	: Tuple must contain at least two elements.
Line 25,41	: ) expected
Line 25,41	: Type or namespace definition, or end-of-file expected
Line 25,74	: Identifier expected
Line 25,74	: Syntax error, ',' expected
Line 25,75	: Tuple must contain at least two elements.
Line 25,76	: Identifier expected
Line 25,77	: ; expected
Line 30,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 25,77	: Type or namespace definition, or end-of-file expected
Line 5710,1	: Type or namespace definition, or end-of-file expected
 InnerException  StackTrace    at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 47
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 58
   at Dapper.Crud.VSExtension.Helpers.ModelHelper.Generate(String[] content, String rawContent, String model) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\ModelHelper.cs:line 10
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 277
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73
"

Imagina o que pode ser?
Estou usando o Dapper 2.0.35.

**Comment by thiagoloureiro** [comment]
Olá Paulo, eu criei uma class Library aqui e coloquei a sua classe:
![image](https://user-images.githubusercontent.com/29433794/95226171-eb8d6f80-07fc-11eb-9ba1-11f791447344.png)

Funcionou normalmente.
O grande detalhe provavelmente é porque você possui algum outro arquivo dentro do seu projeto que está causando o conflito, verifique arquivos que não fazem parte da solution também.
Como recomendação, crie um projeto apenas para os models, caso ainda persista no seu projeto, crie uma solution como eu fiz aqui separadamente e inclua os arquivos lá, a irá gerar normalmente.

Agradeço por utilizar e espero que dê certo!

**Comment by thiagoloureiro** [comment]
```
public class CargosRepository : ICargosRepository
{
    public async Task<IEnumerable<Cargos>> SelectCargos()
    {
        // Select
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"SELECT idCargo, codCargo, cargo, valor, codUni, recursot FROM [Cargos]";

            return await db.QueryAsync<Cargos>(sql, commandType: CommandType.Text);
        }
    }
    public async Task InsertCargos(Cargos cargos)
    {
        // Insert
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"INSERT INTO [Cargos] (idCargo, codCargo, cargo, valor, codUni, recursot) VALUES (@idCargo, @codCargo, @cargo, @valor, @codUni, @recursot)";

            await db.ExecuteAsync(sql, new { idCargo = cargos.idCargo, codCargo = cargos.codCargo, cargo = cargos.cargo, valor = cargos.valor, codUni = cargos.codUni, recursot = cargos.recursot }, commandType: CommandType.Text);
        }
    }
    public async Task UpdateCargos(Cargos cargos)
    {
        // Update
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"UPDATE [Cargos] SET idCargo = @idCargo, codCargo = @codCargo, cargo = @cargo, valor = @valor, codUni = @codUni, recursot = @recursot WHERE idCargo = @idCargo";

            await db.ExecuteAsync(sql, new { idCargo = cargos.idCargo, codCargo = cargos.codCargo, cargo = cargos.cargo, valor = cargos.valor, codUni = cargos.codUni, recursot = cargos.recursot }, commandType: CommandType.Text);
        }
    }
    public async Task DeleteCargos(Cargos cargos)
    {
        // Delete
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"DELETE FROM [Cargos] WHERE idCargo = @idCargo";

            await db.ExecuteAsync(sql, new { cargos.idCargo }, commandType: CommandType.Text);
        }
    }
}
public interface ICargosRepository
{
    Task<IEnumerable<Cargos>> SelectCargos();
    Task InsertCargos(Cargos cargos);
    Task UpdateCargos(Cargos cargos);
    Task DeleteCargos(Cargos cargos);
}
```

**Comment by paulocarinhena** [comment]
Thiagão, eu resolvi fazer o mesmo que você, e criei um projeto do zero só com essa classe:

![image](https://user-images.githubusercontent.com/63272749/95237006-0ac8d480-07de-11eb-999d-edc7199cceb5.png)

Será que ele pode estar dando conflito com alguma extensão?
Eu uso a CodeNav e o "Ef Core Power Tools".

Mas, mesmo em um projeto puro, não deveria ser problema, né?

**Comment by thiagoloureiro** [comment]
Baixa esse projeto:
https://github.com/thiagoloureiro/Dapper.Crud.Extension/blob/master/ClassLibrary2.zip

é o que eu usei como exemplo, ve se dá o mesmo erro aí por favor.

Se puder me enviar seu projeto de teste também olho aqui se tem algo fora

**Comment by paulocarinhena** [comment]
Eu fiz isso, e funcionou!
Bizarro... rs
