### ISSUE TITLE
No tables displayed in list box

### ISSUE THREAD

**Issue by miket4uw** [thiagoloureiro/Dapper.Crud.Extension#21]
My database project has 5 tables.  The Dapper Crud Generator did not list any item.

Which Visual Studio version you have? Microsoft Visual Studio Community 2019, Version 16.0.0
![Screen Shot 2021-03-10 at 11 49 11 PM](https://user-images.githubusercontent.com/6343734/110742184-800c5b80-81fb-11eb-9c18-5f37ed1318cf.png)

Are you using the latest extension version?  3.0.9

**Comment by miket4uw** [comment]
Project Code

[SQLEmploymentDB.zip](https://github.com/thiagoloureiro/Dapper.Crud.Extension/files/6120726/SQLEmploymentDB.zip)

**Comment by thiagoloureiro** [comment]
Hi Mike! thanks for sharing your code.
The extension reads the models (C# Classes) not SQL Files (but interesting that we can add this to the future release). so what you will need to make it work, for example, I created a class for your Address Model:

```
    public class Address
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
    }
```
![image](https://user-images.githubusercontent.com/29433794/110784493-0c556780-826a-11eb-8753-7f0b93e2e2b4.png)

**Result**:

```
public class AddressRepository : IAddressRepository
{
    public async Task<IEnumerable<Address>> SelectAddress()
    {
        // Select
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"SELECT Id, Street, City, State, PostalCode FROM [Address]";

            return await db.QueryAsync<Address>(sql, commandType: CommandType.Text);
        }
    }
    public async Task InsertAddress(Address address)
    {
        // Insert
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"INSERT INTO [Address] (Id, Street, City, State, PostalCode) VALUES (@Id, @Street, @City, @State, @PostalCode)";

            await db.ExecuteAsync(sql, new { Id = address.Id, Street = address.Street, City = address.City, State = address.State, PostalCode = address.PostalCode }, commandType: CommandType.Text);
        }
    }
    public async Task UpdateAddress(Address address)
    {
        // Update
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"UPDATE [Address] SET Id = @Id, Street = @Street, City = @City, State = @State, PostalCode = @PostalCode WHERE Id = @Id";

            await db.ExecuteAsync(sql, new { Id = address.Id, Street = address.Street, City = address.City, State = address.State, PostalCode = address.PostalCode }, commandType: CommandType.Text);
        }
    }
    public async Task DeleteAddress(Address address)
    {
        // Delete
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"DELETE FROM [Address] WHERE Id = @Id";

            await db.ExecuteAsync(sql, new { address.Id }, commandType: CommandType.Text);
        }
    }
}
public interface IAddressRepository
{
    Task<IEnumerable<Address>> SelectAddress();
    Task InsertAddress(Address address);
    Task UpdateAddress(Address address);
    Task DeleteAddress(Address address);
}
```

**Comment by thiagoloureiro** [comment]
Here there are some tricks how you generate classes from Tables:

https://stackoverflow.com/questions/5873170/generate-class-from-database-table

**Comment by miket4uw** [comment]
Thiago,

Thank you for your detailed explanation and the link for the class generation script.  I created a .Net Core library and recieved a compile error message.  I am guessing that the reason is that I need to create a .Net Framework library instead.  I will upload my project in case you would like to take a look.

Thank you,
Mike

Error during the operation: Compiler Errors :
Line 10,28	: The type or namespace name 'Configuration' does not exist in the namespace 'Microsoft.Extensions' (are you missing an assembly reference?)
 InnerException  StackTrace    at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 49
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 61
   at Dapper.Crud.VSExtension.Helpers.ModelHelper.Generate(String[] content, String rawContent, String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\ModelHelper.cs:line 10
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 277
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73 Code using System;
[EmploymentLibrary.zip](https://github.com/thiagoloureiro/Dapper.Crud.Extension/files/6134178/EmploymentLibrary.zip)

**Comment by miket4uw** [comment]
I am closing my issue since the Dapper Crud Generator extension seems intended to work with a .Net Framework project.  I am using a .Net Core project.  I can use the provided error message to obtain the stubbed code for inclusion into my project.  Thank you.

**Comment by thiagoloureiro** [comment]
Hi Mike, isn't for .Net Framework project only.. works for .NET Standard and .NET Core.
I will check your Zip file and get back to you here

**Comment by thiagoloureiro** [comment]
![image](https://user-images.githubusercontent.com/29433794/111553199-2c15ef80-8784-11eb-817b-76c0aa5ada77.png)

**Comment by thiagoloureiro** [comment]
I found a small bug on the component that I will fix, to make the application works I just removed temporarly the DataAccess.cs from the project to generate (there's a bug reading that file that I need to fix) then will manage. Next version I will put a for this scenario :)
