### ISSUE TITLE
Don't work with model C# 10 . CORE 6

### ISSUE THREAD

**Issue by Xepobopa** [thiagoloureiro/Dapper.Crud.Extension#24]
Model:
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Dapper;
using Dapper.Contrib;

namespace CRUDCreator.Models
{
    public class Model
    {
        public int Id { get; set; }
        public int Age { get; set; }
        public string Name { get; set; }
        public string Second_name { get; set; }
    }
}
`

Error: 
`Error during the operation: Object reference not set to an instance of an object. InnerException  StackTrace    at System.Object.GetType()
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 76
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 278
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73 Code 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Dapper;
using Dapper.Contrib;
using System.Collections;
using System.Threading;
using System.ComponentModel;

namespace CRUDCreator.Models
{
    public class Model
    {
        public int Id { get; set; }
        public int Age { get; set; }
        public string Name { get; set; }
        public string Second_name { get; set; }
    }
}
`
![Знімок екрана 2022-11-13 151130](https://user-images.githubusercontent.com/97175414/201523379-4826d0d1-0bfc-4068-9b15-244a2630032c.jpg)

Also there aren't full docs. I don't understand what model you want.

**Comment by thiagoloureiro** [comment]
issue fixed on the last versions:

![image](https://user-images.githubusercontent.com/29433794/236622286-158a6260-75cf-40cc-9818-cf32d0b95583.png)


Keep in mind that the class name needs to have the same name as the file too. check my print screen with all details.

**Comment by thiagoloureiro** [comment]
added a few instructions on the readme to help and directions to sample project:
https://github.com/thiagoloureiro/Dapper.Crud.Extension/blob/master/README.md

Let me know if it works for you.
