### ISSUE TITLE
Error: Assembly and module attributes must precede all other elements

### ISSUE THREAD

**Issue by thatusualguy** [thiagoloureiro/Dapper.Crud.Extension#25]
Error when trying to generate. 

Ouput log (truncated my models listing)
```
Error during the operation: Compiler Errors :
Line 112,10	: #warning: 'To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.'
Line 609,2	: Assembly and module attributes must precede all other elements defined in a file except using clauses and extern alias declarations
Line 611,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 612,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 613,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 614,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 615,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 616,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 617,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
 InnerException  StackTrace    в Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) в C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:строка 49
   в Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) в C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:строка 61
   в Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) в C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:строка 278
   в Dapper.Crud.VSExtension.frmExtension.GenerateCrud() в C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:строка 73 Code using System;
```

`.csproj` listing
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="efpt.config.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="efpt.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.3" />
  </ItemGroup>

</Project>
```
Version and used parameters
![image](https://user-images.githubusercontent.com/76885701/227746129-10493018-070a-49e7-9b92-b0c5af3c9a97.png)

**Comment by andylim-mkj** [comment]
+1. Here's my output log:

Error during the operation: Compiler Errors :
Line 72,11	: File-scoped namespace must precede all other members in a file.
Line 1,39	: The type or namespace name 'Server' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
Line 4,32	: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
Line 82,11	: Source file can only contain one file-scoped namespace declaration.
Line 92,11	: Source file can only contain one file-scoped namespace declaration.
Line 101,11	: Source file can not contain both file-scoped and normal namespace declarations.
Line 17,48	: The type or namespace name 'CircuitHandler' could not be found (are you missing a using directive or an assembly reference?)
Line 105,31	: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?)
Line 49,22	: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Line 26,51	: The type or namespace name 'Circuit' could not be found (are you missing a using directive or an assembly reference?)
Line 32,51	: The type or namespace name 'Circuit' could not be found (are you missing a using directive or an assembly reference?)
Line 103,6	: The type or namespace name 'ResponseCacheAttribute' could not be found (are you missing a using directive or an assembly reference?)
Line 103,6	: The type or namespace name 'ResponseCache' could not be found (are you missing a using directive or an assembly reference?)
Line 104,6	: The type or namespace name 'IgnoreAntiforgeryTokenAttribute' could not be found (are you missing a using directive or an assembly reference?)
Line 104,6	: The type or namespace name 'IgnoreAntiforgeryToken' could not be found (are you missing a using directive or an assembly reference?)
Line 103,20	: The type or namespace name 'Duration' could not be found (are you missing a using directive or an assembly reference?)
Line 103,34	: The type or namespace name 'Location' could not be found (are you missing a using directive or an assembly reference?)
Line 103,45	: The name 'ResponseCacheLocation' does not exist in the current context
Line 103,73	: The type or namespace name 'NoStore' could not be found (are you missing a using directive or an assembly reference?)
Line 107,22	: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Line 111,26	: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?)
Line 113,27	: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?)
 InnerException  StackTrace    at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 49
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 61
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 278
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73 Code using Microsoft.AspNetCore.Components.Server.Circuits;

**Comment by thiagoloureiro** [comment]
can you please paste the content of the class here if possible? @thatusualguy

**Comment by thiagoloureiro** [comment]
I updated the readme with some instructions to help as well and a new sample project

https://github.com/thiagoloureiro/Dapper.Crud.Extension/blob/master/README.md

**Comment by andylim-mkj** [comment]
Thiago,
Thks for the reply. Sure I’ll check it out later.

Rgds,
Andy
