### ISSUE TITLE
ignoring byte type on model

### ISSUE THREAD

**Issue by xgame92** [thiagoloureiro/Dapper.Crud.Extension#4]
When generating the CRUD string. Program ignores byte property type.

**Comment by thiagoloureiro** [comment]
@xgame92 I'm investigating this issue, i have added support to byte type, but didn't worked as you mentioned, will do a fix soon

**Comment by thiagoloureiro** [comment]
Fixed on: https://github.com/thiagoloureiro/Dapper.Crud.Extension/commit/1183ca4cc6b0d175ac50935bc9e57150249ff33a

Version 2.8 will be released by now
