### ISSUE TITLE
inserted id

### ISSUE THREAD

**Issue by csbudai** [thiagoloureiro/Dapper.Crud.Extension#7]
I request a nice to have functionality
inserted id should be updated back to the model:

```
            // Insert
            using (var db = new SqlConnection(connstring))
            {
                string sql = @"INSERT INTO [Person] (Name, Description) VALUES (@Name, @Description);select last_insert_rowid();";
                var id=await db.QueryAsync(sql, new { Name = person.Name, Description = person.Description }, commandType: CommandType.Text);
                person.Id = id;
            }
```
sqlite `select last_insert_rowid();`
Sql `select @@IDENTITY;`

What do you think?

**Comment by thiagoloureiro** [comment]
Sounds good!
Will work on it !

**Comment by thiagoloureiro** [comment]
@csbudai work completed

https://github.com/thiagoloureiro/Dapper.Crud.Extension/releases/tag/3.0.7

Please try the latest version 3.0.7 and let me know if works fine for you
