### ISSUE TITLE
Error during the operation: Compiler Errors

### ISSUE THREAD

**Issue by mafering** [thiagoloureiro/Dapper.Crud.Extension#8]
HI.
Error during the operation: Compiler Errors :
Line 12,10	: The type or namespace name 'HiddenInputAttribute' could not be found (are you missing a using directive or an assembly reference?)
Line 12,10	: The type or namespace name 'HiddenInput' could not be found (are you missing a using directive or an assembly reference?)
Line 12,22	: The type or namespace name 'DisplayValue' could not be found (are you missing a using directive or an assembly reference?)
Line 14,10	: The type or namespace name 'RequiredAttribute' could not be found (are you missing a using directive or an assembly reference?)
Line 14,10	: The type or namespace name 'Required' could not be found (are you missing a using directive or an assembly reference?)
Line 14,19	: The type or namespace name 'ErrorMessage' could not be found (are you missing a using directive or an assembly reference?)
 InnerException  StackTrace    at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 46
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 57
   at Dapper.Crud.VSExtension.Helpers.ModelHelper.Generate(String[] content, String rawContent, String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\ModelHelper.cs:line 10
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 274
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 74

**Comment by thiagoloureiro** [comment]
Hi, can you share your class (model) content that you’re trying to generate?

**Comment by thiagoloureiro** [comment]
https://github.com/thiagoloureiro/Dapper.Crud.Extension/pull/10

**Comment by thiagoloureiro** [comment]
Release 3.0.5 fixes this issue, will close, if persists let me know.

**Comment by mafering** [comment]
Hi. The version is: 3.0.5 and Model Class is:

using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace model.DEL
{
    public class ProgramaDEL
    {
        [HiddenInput(DisplayValue = false)]
        public int IdPrograma { get; set; }
        [Required(ErrorMessage = "Ingrese Nombre del Programa")]
        public string Nombre { get; set; }
        public string Abreviatura { get; set; }
        public decimal Parametro { get; set; }
        public Boolean Estado { get; set; }
        public DateTime Fecha_Add { get; set; }
        public DateTime Fecha_Upd { get; set; }
    }
}

**Comment by thiagoloureiro** [comment]
Hi, is still breaking with the latest version? one quick trick you can comment the hiddeninput and required field should work. Let me know.

**Comment by thiagoloureiro** [comment]
I deployed a new release
can you try again?
gracias

https://github.com/thiagoloureiro/Dapper.Crud.Extension/pull/11

**Comment by mafering** [comment]
Problem resulted. Thanks
